# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec: SuperTory local HTTP backend (app.py + web + db)."""

from __future__ import annotations

import sys
from pathlib import Path

from PyInstaller.utils.hooks import collect_all, collect_submodules

ROOT = Path(SPECPATH).resolve()

datas = [
    (str(ROOT / "web"), "web"),
    (str(ROOT / "db"), "db"),
    (str(ROOT / "assets"), "assets"),
]
_persona_seed = ROOT / "data" / "virtual_reader_personas.json"
if _persona_seed.is_file():
    datas.append((str(_persona_seed), "data"))
# Ship project .env into MEIPASS when present so frozen loaders find GEMINI_API_KEY.
if (ROOT / ".env").is_file():
    datas.append((str(ROOT / ".env"), "."))

binaries: list = []
hiddenimports = [
    "chapter_match",
    "character_import_analysis",
    "scene_cast_detect",
    "document_export",
    "document_import",
    "folder_tree",
    "import_hierarchy",
    "success_pattern",
    "env_loader",
    "bundled_env",  # build-time defaults (generated by scripts/build_backend.py)
    "gemini_client",
    "korean_speller",
    "project_package",
    "world_import_analysis",
    "proof_clean",
    "proof_diff",
    "proof_extract",
    "proof_pipeline",
    "sync",
    "sync.supabase_client",
    "sync.device",
    "sync.pairing",
    "sync.project_sync",
    # stdlib modules sometimes missed under freeze
    "sqlite3",
    "http.server",
    "html.parser",
    "xml.etree.ElementTree",
    "urllib.request",
    "urllib.error",
    "email",
    "email.mime",
    "email.mime.text",
    "email.mime.multipart",
]

# Optional proof/import parsers (include when installed on the build machine).
for pkg in ("docx", "olefile", "six", "hwp5", "lxml", "supabase"):
    try:
        collected = collect_all(pkg)
        datas += collected[0]
        binaries += collected[1]
        hiddenimports += collected[2]
    except Exception as exc:  # noqa: BLE001 — optional packaging
        print(f"[spec] skip collect_all({pkg}): {exc}", file=sys.stderr)
    try:
        hiddenimports += collect_submodules(pkg)
    except Exception:
        pass

a = Analysis(
    [str(ROOT / "app.py")],
    pathex=[str(ROOT)],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="supertory-server",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,  # no extra console window; Electron captures logs via pipes
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(ROOT / "assets" / "icon.ico") if (ROOT / "assets" / "icon.ico").is_file() else None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="supertory-server",
)
