"""Build a standalone SuperTory Python backend with PyInstaller.

Output:
  backend-dist/supertory-server/supertory-server.exe  (+ _internal/)

Also embeds GEMINI_API_KEY / GEMINI_MODEL and the Supabase pairing keys
from the project .env into ``bundled_env.py`` so the frozen server works
without a user-supplied .env.

Usage (from repo root):
  python scripts/build_backend.py
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DIST = ROOT / "backend-dist"
WORK = ROOT / "build" / "pyinstaller"
SPEC = ROOT / "supertory-server.spec"
SERVER_NAME = "supertory-server"
BUNDLED_ENV_PY = ROOT / "bundled_env.py"

# Keys copied from .env into the frozen fallback module.
BUNDLE_KEYS = (
    "GEMINI_API_KEY",
    "GEMINI_MODEL",
    "SUPABASE_URL",
    "SUPABASE_ANON_KEY",
)
SUPABASE_KEYS = (
    "SUPABASE_URL",
    "SUPABASE_ANON_KEY",
)


def ensure_pyinstaller() -> None:
    try:
        import PyInstaller  # noqa: F401
    except ImportError:
        print("Installing PyInstaller…")
        subprocess.check_call(
            [sys.executable, "-m", "pip", "install", "pyinstaller>=6.0"],
            cwd=ROOT,
        )


def _parse_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.is_file():
        return values
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[7:].strip()
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
            value = value[1:-1]
        if key:
            values[key] = value
    return values


def write_bundled_env() -> dict[str, str]:
    """Generate bundled_env.py from project .env for freeze-time defaults."""
    env_path = ROOT / ".env"
    parsed = _parse_env_file(env_path)
    selected: dict[str, str] = {}
    for key in BUNDLE_KEYS:
        value = (parsed.get(key) or os.environ.get(key) or "").strip()
        if value and value not in {"your_gemini_api_key_here", "changeme"}:
            selected[key] = value

    if "GEMINI_API_KEY" not in selected:
        print(
            "WARNING: GEMINI_API_KEY not found in .env — frozen AI features will "
            "need a user-supplied key.",
            file=sys.stderr,
        )
    else:
        print(
            f"Embedding GEMINI_API_KEY into bundled_env.py "
            f"(len={len(selected['GEMINI_API_KEY'])})."
        )

    missing_supabase = [key for key in SUPABASE_KEYS if key not in selected]
    if missing_supabase:
        print(
            "WARNING: Supabase keys missing from .env — frozen sync will stay "
            f"offline until they are supplied ({', '.join(missing_supabase)}).",
            file=sys.stderr,
        )
    else:
        print("Embedding Supabase credentials into bundled_env.py.")

    lines = [
        '"""Build-time env defaults for the frozen SuperTory backend.',
        "",
        "AUTO-GENERATED by scripts/build_backend.py — do not edit or commit.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "BUNDLED_ENV: dict[str, str] = {",
    ]
    for key, value in selected.items():
        lines.append(f"    {key!r}: {value!r},")
    lines.append("}")
    lines.append("")
    BUNDLED_ENV_PY.write_text("\n".join(lines), encoding="utf-8")
    return selected


def _clear_path(path: Path) -> None:
    """Remove a build output path; if locked, rename it aside."""
    if not path.exists():
        return
    try:
        shutil.rmtree(path)
        return
    except OSError:
        pass
    trash = path.with_name(f"{path.name}.old_{os.getpid()}")
    if trash.exists():
        shutil.rmtree(trash, ignore_errors=True)
    try:
        path.rename(trash)
        print(f"Note: could not delete locked {path.name}; moved aside to {trash.name}")
    except OSError as exc:
        raise SystemExit(
            f"Cannot clear {path} (file in use). "
            "Close SuperTory / Explorer windows on that folder, then retry.\n"
            f"{exc}"
        ) from exc


def main() -> int:
    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if callable(reconfigure):
            try:
                reconfigure(encoding="utf-8", errors="replace")
            except Exception:
                pass

    ensure_pyinstaller()
    write_bundled_env()

    _clear_path(DIST / SERVER_NAME)
    _clear_path(WORK)
    DIST.mkdir(parents=True, exist_ok=True)

    cmd = [
        sys.executable,
        "-m",
        "PyInstaller",
        "--noconfirm",
        "--clean",
        str(SPEC),
        "--distpath",
        str(DIST),
        "--workpath",
        str(WORK),
    ]
    print("Running:", " ".join(cmd))
    subprocess.check_call(cmd, cwd=ROOT)

    exe = DIST / SERVER_NAME / f"{SERVER_NAME}.exe"
    if not exe.is_file():
        # Some layouts put the binary directly under distpath/name
        alt = DIST / f"{SERVER_NAME}.exe"
        if alt.is_file():
            print(f"Backend built (onefile?): {alt}")
            _copy_env_sidecar(alt.parent)
            return 0
        print(f"ERROR: expected backend binary not found: {exe}", file=sys.stderr)
        return 1

    _copy_env_sidecar(exe.parent)
    print(f"Backend ready: {exe}")
    return 0


def _copy_env_sidecar(target_dir: Path) -> None:
    """Also place .env next to the exe (exe-dir discovery path)."""
    src = ROOT / ".env"
    if not src.is_file():
        return
    dest = target_dir / ".env"
    shutil.copy2(src, dest)
    print(f"Copied .env sidecar → {dest}")


if __name__ == "__main__":
    raise SystemExit(main())
